### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'schemas' of undefined

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#180]
Production site has the following errors on a continued basis:

```
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'schemas' of undefined
    at asyncData (components/StoryHead.vue:4:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dmonark** [comment]
Same @deshetti  #160 ?

**Comment by KriAga** [comment]
@deshetti are we still seeing this issue in the prod?
